// <auto-generated />
namespace newGigHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview1-19506-01")]
    public sealed partial class Addfk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addfk));
        
        string IMigrationMetadata.Id
        {
            get { return "201910181220295_Addfk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
